filename:
  description: Name of this file
  value:
    type: string
    default: default_temperature.cfg
    units: '-'
run_description:
  description: Description of this configuration
  value:
    type: string
    default: north slope subset cruNCEP
    units: '-'
run_region:
  description: General location of this domain
  value:
    type: string
    default: Alaska
    units: '-'
run_resolution:
  description: High- or low-resolution data
  value:
    type: string
    default: lowres
    units: '-'
reference_date:
  description: Model time is relative to this date
  value:
    type: string
    default: '1900-01-01'
    units: '-'
model_start_year:
  description: First year with valid model data
  value:
    type: long
    default: 1902
    units: yr
model_end_year:
  description: Last year with valid model data
  value:
    type: long
    default: 1910
    units: yr
grid_name:
  description: Name of the model grid
  value:
    type: string
    default: temperature
    units: '-'
grid_type:
  description: Form of the model grid
  value:
    type: string
    default: uniform_rectilinear
    units: '-'
grid_columns:
  description: Number of columns in model grid
  value:
    type: int
    default: 40
    units: '-'
grid_rows:
  description: Number of rows in model grid
  value:
    type: int
    default: 20
    units: '-'
i_ul:
  description: I-coordinate of upper left model domain
  value:
    type: int
    default: 50
    units: '-'
j_ul:
  description: J-coordinate of upper left model domain
  value:
    type: int
    default: 25
    units: '-'
timestep:
  description: Model time step
  value:
    type: int
    default: 1
    units: yr
